name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *' # Runs at 12:00 AM IST (6:30 PM UTC)

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "ðŸ“Š Updated WakaTime Stats"
          COMMIT_USERNAME: "skp3214"
